use serde::{Serialize, Deserialize};

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct WorkOrderStatusStore {
    pub Id: String,
    pub Created: String,
    pub CreatedId: String,
    pub Changed: String,
    pub ChangedId: String,
    pub Disabled: String,
    pub StatusName: String,
    pub StatusCode: String,
    pub StatusColor: String,
    pub Notify: String,
    pub TotalCount: String,
    pub SecReadOnly: String,
    pub SecAccessRight: String
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct UserWorkOrderListStore {
    pub Id: String,
    pub Created: String,
    pub CreatedId: String,
    pub Changed: String,
    pub ChangedId: String,
    pub Disabled: String,
    pub TotalCount: String,
    pub WorkOrderId: String,
    pub ProjectId: String,
    pub ProjectName: String,
    pub ProjectNo: String,
    pub ProjectStatusCode: String,
    pub WorkOrderStatusCode: String,
    pub HaveDocument: String,
    pub WorkOrderNo: String,
    pub Addition: String,
    pub Name: String,
    pub CustomerId: String,
    pub CustomerName: String,
    pub ResponsibleServiceId: String,
    pub ResponsibleForemanId: Option<String>,
    pub ProductionStart: String,
    pub WorkOrderStatusId: String,
    pub WorkOrderStatusColor: String,
    pub CustomerFavoritePriceList: String,
    pub ProjectFavorite: String,
    pub CustomerFavoriteArticlePrice: String,
    pub Closed: String,
    pub SecReadOnly: String,
    pub SecAccessRight: String
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize, Clone)]
pub struct WorkOrderStore {
    pub Id: String,
    pub Created: String,
    pub CreatedId: String,
    pub Changed: String,
    pub ChangedId: String,
    pub Disabled: String,
    pub ProjectId: String,
    pub WorkOrderNo: String,
    pub Addition: String,
    pub Name: String,
    pub ResponsibleForemanId: Option<String>,
    pub CustomerId: String,
    pub CustomerRefNo: Option<String>,
    pub WorkOrderStatusId: String,
    pub SignOnSite: String,
    pub ProductionStart: Option<String>,
    pub ProductionEnd: Option<String>,
    pub OrderDate: Option<String>,
    pub Reminder: String,
    pub ContractorVat: String,
    pub HideMarkup: String,
    pub Closed: String,
    pub TotalCount: String,
    pub ProjectNo: String,
    pub BookedCostTotal: Option<String>,
    pub BookedHoursTotal: Option<String>,
    pub WorkOrderStatusCode: String,
    pub HaveDocument: String,
    pub InvoicedAll: String,
    pub StatusName: String,
    pub CreatedName: String,
    pub ChangedName: String,
    pub CustomerName: String,
    pub ResponsibleForemanName: Option<String>,
    pub CustomerPriceTotal: Option<String>,
    pub CustomerTypeName: String,
    pub WorkDescription: Option<String>,
    pub CachedEarnedNotInvoiced: Option<String>,
    pub InvoiceableMarkup: Option<String>,
    pub ContributionMargin: Option<String>,
    pub SecAccessRight: String,
    pub SecReadOnly: String,
    pub WorkFeedback: Option<String>,
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct UserProjectWorkOrderListStore {
    pub Id : String,
    pub Created : String,
    pub CreatedId : String,
    pub Changed : String,
    pub ChangedId : String,
    pub Disabled : String,
    pub TotalCount : String,
    pub WorkOrderId : String,
    pub ProjectId : String,
    pub ProjectName : String,
    pub ProjectNo : String,
    pub ProjectStatusCode : String,
    pub WorkOrderStatusCode : String,
    pub HaveDocument : String,
    pub WorkOrderNo : String,
    pub Addition : String,
    pub Name : String,
    pub CustomerId : String,
    pub CustomerName : String,
    pub ResponsibleForemanId : String,
    pub ProductionStart : String,
    pub WorkOrderStatusId : String,
    pub WorkOrderStatusColor : String,
    pub CustomerFavoritePriceList : String,
    pub ProjectFavorite : String,
    pub CustomerFavoriteArticlePrice : String,
    pub Closed : String,
    pub SecReadOnly : String,
    pub SecAccessRight : String
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct WorkOrderDocumentStore {
    pub Id : String,
    pub Created : String,
    pub CreatedId : String,
    pub Changed : String,
    pub ChangedId : String,
    pub Disabled : String,
    pub TotalCount : String,
    pub CreatedName : String,
    pub ChangedName : String,
    pub IsFolder : String,
    pub HasChildren : String,
    pub WorkOrderId : String,
    pub DocumentDescription : String,
    pub DocumentMimeType : String,
    pub DocumentSize : String,
    pub ImageWidth : String,
    pub ImageHeight : String,
    pub EnlargeInReports : String,
    pub Name : String,
    pub Title : String,
    pub ThumbnailMimeType : String,
    pub ThumbnailData : String,
    pub Filename : String,
    pub HideInPDA : String,
    pub IncludeOnOffer : String,
    pub ProjectId : String,
    pub WorkOrderNo : String,
    pub WorkOrderStatusColor : String,
    pub Addition : String,
    pub ShowInPortal : String,
    pub IncludeInReport : String,
    pub ProjectNo : String,
    pub ProjectStatusColor : String,
    pub RegDate : String,
    pub FileLastModified : String,
    pub DocOnlineFolderId :String,
    pub ExternalId : String,
    pub ProcurementFolder : String,
    pub DeviationFolder : String,
    pub FictiveFolder : String,
    pub Editable : String,
    pub WOAWONo : String,
    pub SecReadOnly : String,
    pub SecAccessRight : String
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct ProjectListStore {
    pub Id : String,
    pub Created : String,
    pub CreatedId : String,
    pub Changed : String,
    pub ChangedId : String,
    pub Disabled : String,
    pub TotalCount : String,
    pub ProjectNo : String,
    pub ProjectId : String,
    pub ProjectStatusId : String,
    pub StatusCode : String,
    pub StatusName : String,
    pub ProjectName : String,
    pub CustomerId : String,
    pub WorkplaceId : String,
    pub StatusColor : String,
    pub Piecework : String,
    pub CustomerRef : String,
    pub SecReadOnly : String,
    pub SecAccessRight : String
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct UserRightStore {
    pub AdminClient : String,
    pub ApiClient : String,
    pub Changed : String,
    pub ChangedId : String,
    pub Created : String,
    pub CreatedId : String,
    pub Disabled : String,
    pub Id : String,
    pub IsBaseApiRight : String,
    pub MobileClient : String,
    pub ObjectName : String,
    pub ObjectRightId : String,
    pub ObjectRightName : String,
    pub TotalCount : String,
    pub UserId : String,
    pub WebClient : String,
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct OptionValueStore {
    pub Changed : String,
    pub ChangedId : String,
    pub Created : String,
    pub CreatedId : String,
    pub Disabled : String,
    pub Id : String,
    pub SecAccessRight : String,
    pub SecReadOnly : String,
    pub SettingKey : String,
    pub SettingValue : String,
    pub TotalCount : String,
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct UserListStore {
    pub Changed : String,
    pub ChangedId : String,
    pub Created : String,
    pub CreatedId : String,
    pub Disabled : String,
    pub DocOnlineActive : String,
    pub DocOnlineInvited : String,
    pub Email : String,
    pub EmployeeNo : String,
    pub FullName : String,
    pub HasPhone1 : String,
    pub HasPhone2 : String,
    pub Id : String,
    pub PartnerSupplier : String,
    pub PersonalNo : Option<String>,
    pub PlanningActive : String,
    pub ProfessionCode : String,
    pub ProfessionItemId : String,
    pub SecAccessRight : String,
    pub SecReadOnly : String,
    pub Signature : String,
    pub TotalCount : String,
    pub UserLogin : String,
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct OfficeCompanyStore {
    pub AbsenceProjectId : String,
    pub BICNo : String,
    pub Bankgiro : String,
    pub Changed : String,
    pub ChangedId : String,
    pub CompanyName : String,
    pub CompanyWeb : String,
    pub Created : String,
    pub CreatedId : String,
    pub Disabled : String,
    pub EdiAddress : String,
    pub Email : String,
    pub FTaxApproved : String,
    pub FTaxText : String,
    pub Fax : String,
    pub IBANNo : String,
    pub Id : String,
    pub InvoiceContactEmail : String,
    pub InvoiceContactName : String,
    pub LogoData : String,
    pub LogoMimeType : String,
    pub LogoUUID : String,
    pub OrganizationNo : String,
    pub PenaltyInterestText : String,
    pub Phone : String,
    pub Plusgiro : String,
    pub PostalAddress1 : String,
    pub PostalAddress2 : String,
    pub PostalAddress3 : String,
    pub PostalAddress4 : String,
    pub PostalAddress5 : String,
    pub PostalAddress6 : String,
    pub SecAccessRight : String,
    pub SecReadOnly : String,
    pub TotalCount : String,
    pub VatNo : String,
    pub VisitAddress1 : String,
    pub VisitAddress2 : String,
    pub VisitAddress3 : String,
    pub VisitAddress4 : String,
    pub VisitAddress5 : String,
    pub VisitAddress6 : String,
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct UserAccessStore {
    pub AccessRight : String,
    pub AdminClient : String,
    pub ApiClient : String,
    pub Changed : String,
    pub ChangedId : String,
    pub Created : String,
    pub CreatedId : String,
    pub Disabled : String,
    pub Id : String,
    pub IsBaseApiRight : String,
    pub IsProjectRight : String,
    pub MobileClient : String,
    pub ObjectName : String,
    pub ObjectRightId : String,
    pub ObjectRightName : String,
    pub OwnRight : String,
    pub ReadRight : String,
    pub SecAccessRight : String,
    pub SecReadOnly : String,
    pub TotalCount : String,
    pub UserId : String,
    pub WebClient : String,
    pub WriteRight : String,
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct UserSessionStore {
    pub Changed : String,
    pub ChangedId : String,
    pub Comment : String,
    pub Created : String,
    pub CreatedId : String,
    pub Disabled : String,
    pub Id : String,
    pub ImpersonatedUserId : String,
    pub Languagecode : String,
    pub SessionId : String,
    pub SessionType : String,
    pub SessionUserId : String,
    pub TotalCount : String,
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct WorkOrderListStore {
    pub Addition : String,
    pub Changed : String,
    pub ChangedId : String,
    pub Closed : String,
    pub Created : String,
    pub CreatedId : String,
    pub CustomerFavoriteArticlePrice : String,
    pub CustomerFavoritePriceList : String,
    pub CustomerId : String,
    pub CustomerName : String,
    pub Disabled : String,
    pub HaveDocument : String,
    pub Id : String,
    pub Name : String,
    pub ProjectFavorite : String,
    pub ProjectId : String,
    pub ProjectName : String,
    pub ProjectNo : String,
    pub ProjectStatusCode : String,
    pub SecAccessRight : String,
    pub SecReadOnly : String,
    pub TotalCount : String,
    pub WorkOrderId : String,
    pub WorkOrderNo : String,
    pub WorkOrderStatusCode : String,
    pub WorkOrderStatusColor : String,
    pub WorkOrderStatusId : String,
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize, Clone)]
pub struct ProjectLimitedStore {
    pub BasicScopeId : String,
    pub Changed : String,
    pub ChangedId : String,
    pub CostCenterId : String,
    pub Created : String,
    pub CreatedId : String,
    pub CustomerId : String,
    pub CustomerRef : String,
    pub Disabled : String,
    pub Id : String,
    pub MarkupModelId : String,
    pub ParentProjectId : String,
    pub PriceTypeId : String,
    pub ProjectId : String,
    pub ProjectManagerId : String,
    pub ProjectName : String,
    pub ProjectNo : String,
    pub ProjectStatusCode : String,
    pub ProjectStatusId : String,
    pub SecAccessRight : String,
    pub SecReadOnly : String,
    pub TotalCount : String,
    pub WOFavorite : String,
    pub WorkplaceId : String,
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize, Clone)]
pub struct ChecklistRowStore {
    pub Changed : String,
    pub ChangedId : String,
    pub CheckNote : String,
    pub Checked : String,
    pub Created : String,
    pub CreatedId : String,
    pub Disabled : String,
    pub Id : String,
    pub ItemDescription : String,
    pub ItemNo : String,
    pub ProjectId : String,
    pub SecAccessRight : String,
    pub SecReadOnly : String,
    pub TotalCount : String,
    pub WorkOrderId : String,
}
